model_name: DeepSet_Snapshot
batch_size: 16
learning_rate: 3e-5
epochs: 100
Debug: False
keep_init_real: False
num_workers: 8
Is_shuffle: False
Is_drop_last: True
step_size: 10
gamma: 0.1
padding_columns: None
check_dataset: True
features_len: 6
output_size: 3
deepset_hidden_size: 2048
deepset_out_size: 1024
eps: 1e-7