model_name: DeepSet_Only
batch_size: 64
learning_rate: 3e-7
epochs: 100
keep_init_real: False
Debug: False
num_workers: 8
hidden_size: 1024
Is_shuffle: False
Is_drop_last: True
step_size: 10
gamma: 0.1
padding_columns: None
check_dataset: True
features_len: 6
output_size: 3
eps: 1e-6