model_name: DeepSet_Dense
batch_size: 64
learning_rate: 3e-6
epochs: 100
Debug: False
keep_init_real: False
num_workers: 8
Is_shuffle: False
Is_drop_last: True
step_size: 10
gamma: 0.1
padding_columns: None
check_dataset: True
deepset_hidden_size: 2048
features_len: 6
output_size: 3
deepset_out_size: 64
eps: 1e-7