model_name: DeepSet_Only
batch_size: 16
learning_rate: 3e-5
epochs: 100
keep_init_real: False
Debug: False
num_workers: 8
hidden_size: 2048
Is_shuffle: False
Is_drop_last: True
step_size: 5
gamma: 0.1
padding_columns: None
check_dataset: True
features_len: 6
output_size: 3
eps: 1e-6